//
//  Constatnts.swift
//  MyApp
//
//  Created by Satsishur on 25.05.2020.
//  Copyright © 2020 Consumeda. All rights reserved.
//

import Foundation


enum Constants {
    static let databaseId = "id"
    static let mailgunDomain = "domain"
    static let mailgunAPIkey = "key"
    
    static let policy = """
    UAB „Consumeda“ during the processing of personal data complies with the highest standards, respects and always implements rights of personal data subjects, because of that invites You to read privacy policy of UAB “Consumeda“ processed personal data (hereinafter – Policy).
    
    PRIVACY POLICY OF PERSONAL DATA

    UAB „Consumeda“ is a limited liability company register in the Republic of Lithuania, which legal entity‘s code is 303050100 and registered office address is Filaretų str. 99A, Vilnius, Lithuania, phone No. +37068453384, email consumeda3@gmail.com. The scope of UAB „Consumeda“ activity is trade in medical devices.
    
    DEFINITIONS:
    •    Personal data means any information relating to an identified or identifiable natural person, including but not limited name, surname, personal code, date of birth, address, phone number, email address.
    •    Personal data provision means actions of any information transference to other person, for example, document sending by email.
    •    Personal data processing means operation or set of operations which is performed on personal data or on sets of personal data, whether or not by automated means, such as collection, recording, organisation, structuring, storage, adaptation or alteration, retrieval, consultation, use, disclosure by transmission, dissemination or otherwise making available, alignment or combination, restriction, erasure or destruction.
    •    GDPR means a legal act, which is valid in all European Union teritorry and called as „Regulation (EU) 2016/679 of the European Parliament and of the Council of 27 April 2016 on the protection of natural persons with regard to the processing of personal data and on the free movement of such data, and repealing Directive 95/46/EC“ annd which is linked at https://eur-lex.europa.eu/legal-content/EN/TXT/HTML/?uri=CELEX:32016R0679&from=EN.
    •    Data subject means natural person who is personal data are processed in the activity of personal data controller.
    •    Data controller is UAB „Consumeda“, legal entity‘s code 303050100, registered office address Filaretų str. 99A, Vilnius, Lithuania, phone No. +37068453384, email consumeda3@gmail.com, which processes Yours personal data.
    •    Data processor is UAB “Tako Plius”, legal entity’s code 301817798, address Vingrių str. 6A, Vilnius, Lithuania, phone No. +370 5 24 835 93, email info@takoplius.lt, which process UAB “Consumeda” employees and contractors (natural persons) data on the behalf of UAB “Consumeda” due to accountancy.
    •    Website means a website which belongs to UAB „Consumeda“ and the link is http://www.consumeda.com.
    •    Contractor means legal or natural person, who / which is engaged in commercial activity and who / which provides services, performs works or supplies goods to UAB „Consumeda“ or mentioned person purchases goods from UAB „Consumeda“.
    •    Cookies means small amount of data (up to a few KB) generated by a visited website www.consumeda.com and saved by your web browser in computer, tablet, mobile phone or other smart device. Its purpose is to remember type of chosen language in a website.
    •    Agreement means an oral or written bilateral or multilateral transaction.
    •    App means a programm used in mobile phones to submit an order for UAB “Consumeda” and which belongs to UAB “Consumeda”.
    Other definitions used in this Policy comply with definitions used in legal acts.
    
    I. CATEGORIES OF PROCESSED PERSONAL DATA

    UAB „Consumeda“ in a performance of economic – commercial activity process following personal data:
    1. Employees‘ personal data – name, surname, personal code, date of birth, address, phone number, email address, bank account number, position, information about the participation in a supplementary pension accumulation (if pension is accumulated in II stage – rate of accumulation), personal identification documents‘ type (passport, personal identification card, temporary residence card, permanent residence card) and number, copy of personal identification document.
    2. Shareholders‘ personal data – name, surname, personal code, date of birth, address, phone number, email address, copy of personal identification document, citizenship, date of acquiring / loss  and number of shares.
    3. Contractors‘ (natural persons) personal data – name, surname, address, phone number, email address, bank account number, personal code, number of self-employment certificate, number of individual economic activity.
    4. Employees of contractors’ personal data – position, name, surname, phone number, email address.
    5. Website’s visitor personal data who submits a query – name, surname, email address, country.
    6. Natural person who participates in a human recruitment process personal data – curriculum vitea.
    7. Person, who has made order, personal data – name, email address, company’s name, where person works.
    
    II. PURPOSES OF PERSONAL DATA PROCESSING
    
    UAB „Consumeda“ processes personal data only if has clear and justified purposes which are:
    •    In purposes of internal administration, legal obligations implementation and concluded agreement performance, for example, conclusion of employment agreement, salary calculation and payment, information provision to Legal entity‘s register etc. are processed personal data prescribed in chapter I, clauses 1, 2,7 of this Policy;
    •    In purposes of accounting and legal obligation, including, but not limited issuance of invoice, also performance of concluded agreements when contacting with employee who is responsible for goods delivery, supplying, changing, any service provision, work performance etc. Are processed personal data prescribed in chapter I, clauses 3 – 4 of this Policy;
    •    In purposes of reply to clients or potential clients’ queries, any actions performance until conclusion of agreement, are processed personal data prescribed in chapter I, clause 5 of this Policy.
    •    In a purpose of legitimate interest by seeking to choose most suitable employee, to evaluate potential employees competences, education, experience, are processed personal data prescribed in chapter I, clause 6 of this Policy.
    
    III. TERMS OF PERSONAL DATA STORAGE

    Personal data are stored only for the term which is necessary in a activity of UAB „Consumeda“ and obliged by the laws of the Republic of Lithuania:
    •    UAB „Consumeda“ employees data are stored for 50 years as it regulated in Guideline of Terms of Retention of General Documents, approved by the Lithuanian Chief Archivist order No. V-100 on 9 March 2011;
    •    UAB „Consumeda“ shareholders data are stored until UAB „Consumeda“ is registered in VĮ Registrų centras Juridinių asmenų registras;
    •    Service provision / acquisition agreements and other agreements, evidence of economical transactions (invoice, cash / expenses receipts etc.) are stored for 10 years as it regulates Guideline of Terms of Retention of General Documents, approved by the Lithuanian Chief Archivist order No. V-100 on 9 March 2011 if different terms are not stated in a laws;
    •    Website visitor‘s data who submits query is stored not longer than 1 year after the end of communication;
    •    Person, who participates in human recruitment process, personal data are stored not longer than 3 months after the end of recruitment process.
    
    IV. PERSONAL DATA RECEIVING

    UAB „Consumeda“ ussully gets personal data directly from personal data subject, but in some cases personal data might be received from third parties, including, but not limited:
    •    Bailiffs in relation to debt recovery;
    •    Courts, where courts send procedural documents to the employer’s bookkeeping address;
    •    State and municipal institutions as well as other budgetary institutions, where documents, notifications, and protocols cannot be served at the address of the person’s residence;
    
    V. PERSONAL DATA DISCLOSURE

    UAB „Consumeda“ may disclose personal data to following persons:
    •    State and municipal institutions, establishments, and organizations on declaration basis;
    •    Law enforcement agencies;
    •    Payments and credits institutions when shall be made payments according to the agreements;
    •    Accounting and legal service providers;
    •    Shipments delivery companies
    •    To other if there is legal basic.
    
    VI. TERITORRY OF PERSONAL DATA PROCESSING

    UAB „Consumeda“ processes personal data only in the teritorry of European Union.
    
    VII. RIGHTS OF PERSONAL DATA SUBJECTS AND ITS IMPLEMENTATION

    GDPR provides following rights for personal data subjects:
    •    Getting access to the personal data concerning him or her. In order to get access to personal data processed, i.e. what kind of personal data we process, on what basis, and so on, you must submit an application in accordance with Article 15 of GDPR*.
    •    Rectification of personal data. The data subject shall have a right to obtain from UAB “Consumeda” without undue delay the rectification of inaccurate personal data concerning him or her in accordance with Article 16 of GDPR*.
    •    Erasure of personal data or “right to be forgotten”. The data subject shall have a right to obtain from UAB “Tako Plius” the erasure of personal data concerning him or her without undue delay, if the personal data have been unlawfully processed, etc., in accordance with Article 17 of GDPR*.
    •    Restricted processing of personal data. The data subject shall have a right to obtain restriction of processing of personal data, if a) the accuracy of personal data is contested by the data subject for a period enabling UAB “Consumeda” to verify the accuracy of the personal data; b) the processing is unlawful and the data subject opposes the erasure of the personal data and requests the restriction of their use instead; c) UAB “Consumeda” no longer needs the personal data for the purposes of the processing, but they are required by the data subject for the establishment, exercise, or defence of legal claims; or d) the data subject has objected to processing pursuant to Article 21(1) of GDPR* pending the verification whether the legitimate grounds of the controller override those of the data subject.
    •    Portability of personal data. The data subject shall have a right to receive the personal data concerning him or her, which he or she has provided to UAB “Consumeda”, in a structured, commonly used, and machine-readable format and have the right to transmit those data to another controller without hindrance from the controller, to which the personal data have been provided, where: a) the processing is based on consent pursuant to point (a) of Article 6(1) and point (a) of Article 9(2) of GDPR* or on a contract pursuant to point (b) of Article 6(1) of GDPR*; and b) the processing is carried out by automated means.
    
    The data subject may implement his or her rights upon the application submitted to UAB “Consumeda”. The response to the application is submitted no later than within 30 calendar days. The data subject must indicate in the application the identification data of the data subject. Identification data is needed to identify a person and protect personal data from unauthorized disclosure of personal data to third parties. The application may be sent by e-mail consumeda3@gmail.com.
    
    VIII. RIGHT TO SUBMIT A CLAIM

    We would like to inform You that if You think that Your rights are breached You can submit application (claim) to the State Data Protection Inspectorate of the Republic of Lithuania, which contact details is address L. Sapiegos str. 17, Vilnius, Lithuania, Vilnius; email ada@ada.lt; phone No. 8 5 271 2804, 8 5 279 1445.

    IX. COOKIES
    In a website www.consumeda.com of UAB „Consumeda“ is used only one function cooky, which description is below:
    Cooky‘s name: pll_language
    Description: Used to support the language selected by the visitor
    Validity term: 1 year
    
    Visitor may manage cookies in a website www.consumeda.com. Management of cookies depends on what kind of device and browser are used. In links below are prescribed instruction of cookies management:
    •    for „Google Chrome“ – https://support.google.com/chrome/answer/95647?co=GENIE.Platform%3DDesktop&hl=lt;
    •    for „Mozilla Firefox“ – https://support.mozilla.org/lt/kb/Slapuk%C5%B3%20valdymas;
    •    for „Internet Explorer“ – https://support.microsoft.com/lt-lt/help/17442/windows-internet-explorer-delete-manage-cookies;
    •    for „Safari“ – https://support.apple.com/kb/PH21411?viewlocale=en_GB&locale=en_GB;
    •    for „Opera“ – http://help.opera.com/Windows/9.51/en/cookies.html.

    When opened UAB „Consumeda“ website www.consumeda.com are showed information that in website are used cookies.


    X. CHANGES OF PRIVACY POLICY
    If UAB „Consumeda“ decides to change this personal data privacy policy, updated personal data privacy policy will be announced in UAB „Consumeda“ website www.consumeda.com.
"""
}
